Fix Issue #1045.
PyTorchLightning/metrics pull request #1046
Opened 2022-05-25 12:22 UTC by kpoeppel

## What does this PR do?

Fixes Issue #1045, simply copying tensors before they are mutated in-place.

## Before submitting

- [ ] Was this **discussed/approved** via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/metrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to **update the docs**?
- [ ] Did you write any new **necessary tests**? 
 -> Feel free to add the test mentioned in #1045

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

2022-05-25 12:42 UTC, Borda requested changes
pls add the test mentioned in #1045

2022-05-27 00:11 UTC, kpoeppel commented
@SkafteNicki :
I am sorry, somehow I added a wrong bug report code, it is updated now and I also checked it on master now.

@Borda: 
Test will be added now. For the specificity there is no error currently, but it is bad structure to assume that tn can be mutated.

2022-05-27 08:39 UTC, SkafteNicki approved these changes

2022-05-27 09:24 UTC, Borda approved these changes

2022-05-27 09:55 UTC, merged