Improve slow torchmetrics.Accuracy
PyTorchLightning/metrics pull request #609
Opened 2021-11-08 11:36 UTC by puhuk

To resolve issue #485

# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## What does this PR do?

Fixes #485.

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
:]
Make sure you had fun coding 🙃

2021-11-08 13:16 UTC, Borda requested changes

2021-11-08 13:16 UTC, Borda commented on torchmetrics/functional/classification/accuracy.py
> +    except:
pls specify type of exception

2021-11-08 14:19 UTC, justusschock commented
@puhuk as you can see in https://dev.azure.com/PytorchLightning/Metrics/_build/results?buildId=41050&view=logs&j=3afc50db-e620-5b81-6016-870a6976ad29&t=98354d77-e326-51ec-536f-1549451db1fa some of the tests failed with your adjustments

2021-11-08 14:31 UTC, puhuk commented
@justusschock Let me check and resend

2021-11-18 17:06 UTC, Borda commented
@puhuk how is it going here? :rabbit:

2021-11-19 05:24 UTC, puhuk commented
@Borda Sorry for late submission of this PR. Because of some busy works in thesedays, I could not correct the commit. Could you give me some time by next weekend. If it is urgent, it is sure you can assign others to this :)

Sorry for lateness again.

2021-11-19 21:26 UTC, Borda commented
> Could you give me some time by next weekend. If it is urgent, it is sure you can assign others to this :)

sure, no problem :rabbit: just let us know if need even more or other help...
cc: @SkafteNicki

2021-11-24 17:17 UTC, Borda approved these changes

2021-11-24 17:20 UTC, justusschock requested changes
Blocking to wait for @puhuk response and not accidentally merging.

2021-11-25 16:01 UTC, puhuk commented
@Borda Sorry, but may I ask what is changed and why is it approved to merge ??

2021-11-25 16:28 UTC, Borda commented
> Sorry, but may I ask what is changed and why is it approved to merge ??

apology, just overclocked instead of comment...

2022-01-04 20:46 UTC, Borda commented
@puhuk how is it going here? :rabbit:

2022-01-05 11:54 UTC, puhuk commented
@Borda,
Hi, sorry with my mistake. I thought it was approved and merged from PR and review history.
Sorry to bother you but may I ask what is remained with this PR?

2022-01-05 12:13 UTC, Borda commented
> Hi, sorry with my mistake. I thought it was approved and merged from PR and review history. Sorry to bother you but may I ask what is remained with this PR?

check @justusschock comment https://github.com/PyTorchLightning/metrics/pull/609#pullrequestreview-815202418

2022-01-05 13:41 UTC, puhuk commented
> > Hi, sorry with my mistake. I thought it was approved and merged from PR and review history. Sorry to bother you but may I ask what is remained with this PR?
> 
> check @justusschock comment [#609 (review)](https://github.com/PyTorchLightning/metrics/pull/609#pullrequestreview-815202418)

As I checked @justusschock 's comment, there is no review with code and before the comment, I reflected code reviews to the PR.
Could you kindly let me know what I'm missing now.

2022-01-05 16:06 UTC, Borda commented
> Could you kindly let me know what I'm missing now.

- [ ] Do you have benchmarks on how much your implementation is faster?
- [ ] Fix the failing tests :rabbit:

2022-01-06 04:42 UTC, puhuk commented
I leave benchmark as below.
It slightly improve current logic but hard to accomplish the time originally suggested by issue raiser (marsggbo from issue #485)

I tried to correct the failing test cases, but it seems hard for me to resolve and finish this PR.
May I ask to help with this.

```

# 0.161, Accuracy calculation logic of marsggbo (issue #485)
# 1.471  Current accuracy
# 0.297  torchmetrics.functional.accuracy
# 0.901  suggested PR logic

import torch
import torchmetrics
from metrics.torchmetrics.classification import Accuracy as AC

x = torch.rand(256,10)
y = torch.randint(10,(256,))
import timeit

def MyAccuracy(output, target, topk=(1,)):
    """ Computes the precision@k for the specified values of k """
    maxk = max(topk)
    batch_size = target.size(0)

    _, pred = output.topk(maxk, 1, True, True)
    pred = pred.t()
    correct = pred.eq(target.reshape(1, -1).expand_as(pred))

    res = []
    for k in topk:
        correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
        res.append(torch.tensor(correct_k.mul_(100.0 / batch_size)))
    if len(res) == 1:
        return res[-1]
    return res


def f1():
    MyAccuracy(x,y)
def f2():
    torchmetrics.Accuracy()(x,y)
def f3():
    torchmetrics.functional.accuracy(x,y)
def f4():
    # Test with changed accuracy function
    AC()(x,y)

print(timeit.timeit(f1, number=1000)) # 0.161, Accuracy calculation logic of marsggbo (issue #485)
print(timeit.timeit(f2, number=1000)) # 1.471  Current accuracy
print(timeit.timeit(f3, number=1000)) # 0.297  torchmetrics.functional.accuracy
print(timeit.timeit(f4, number=1000)) # 0.901  suggested PR logic

```

2022-02-25 15:09 UTC, SkafteNicki commented
Closing PR as we in the near future is going to refactor the hole classification package (https://github.com/PyTorchLightning/metrics/projects/6) where we can better try to design all classification metrics (at least metrics that inherent from `StatScore`) to be faster.
Thanks for wanting to contribute @puhuk. Your code has made it clear that a large portion of the computational time is spent on input checking and that we should take this into account.

2022-02-25 15:09 UTC, closed without merging