unify f1 score
PyTorchLightning/metrics pull request #731
Opened 2022-01-08 09:29 UTC by cuent

## What does this PR do?

Refactor F1 score

## Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

2022-01-08 09:30 UTC, cuent commented
Should `F1` object be renamed to `F1Score`?

2022-01-08 09:49 UTC, stancld commented
> Should [`F1`](https://github.com/PyTorchLightning/metrics/blob/master/torchmetrics/classification/f_beta.py#L177) object be renamed to `F1Score`?

Yes, please use `F1Score` for the class name :]

2022-01-08 09:51 UTC, stancld commented on docs/source/references/functional.rst
>  ~~~~~~~~~~~~~~~
```suggestion
f1_score [func]
~~~~~~~~~~~~~~~
```

2022-01-08 11:01 UTC, Borda reviewed
- [ ] deprecation warnings & back compatibility
- [ ] rename also `F1` class to be consistent (suggestion `F1Score`)
- [ ] add changelog

part of #729

2022-01-08 11:35 UTC, Borda requested changes
deprecation warnings & back-compatibility, see https://github.com/PyTorchLightning/metrics/pull/731#pullrequestreview-847145436

2022-01-09 08:55 UTC, Borda approved these changes

2022-01-09 08:55 UTC, Borda commented on CHANGELOG.md
> +- Renamed `torchmetrics.functional.f1` to `torchmetrics.functional.f1_score` and `torchmetrics.F1` to `torchmetrics.F1Score` to unify name convention with other frameworks ([#731](https://github.com/
```suggestion
- Renamed F-score metrics: ([#731](https://github.com/PyTorchLightning/metrics/pull/731))
  * `torchmetrics.functional.f1` -> `torchmetrics.functional.f1_score`
  * `torchmetrics.F1` -> `torchmetrics.F1Score`
```

2022-01-09 11:50 UTC, stancld approved these changes

2022-01-09 11:50 UTC, stancld commented on docs/source/references/modules.rst
>  ~~
```suggestion
F1Score
~~~~~~~
```

2022-01-09 21:07 UTC, merged