Rename instances of `manhatten` to `manhattan`
PyTorchLightning/metrics pull request #738
Opened 2022-01-10 17:09 UTC by celynw

## What does this PR do?

Renames instances of `manhatten` to `manhattan`. All I have done is a recursive find/replace and checked the result.

I'm pretty sure it's supposed to be manhattan, isn't it?? But it's so consistent it feels intentional, especially considering the combination of spellings here:
https://github.com/PyTorchLightning/metrics/blob/e6b6fb54f3b700d3e4b773953e9880f7f28e555a/tests/pairwise/test_pairwise_distance.py#L74
So, feel free to deny.

## Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

2022-01-10 18:34 UTC, Borda requested changes

2022-01-10 18:34 UTC, Borda commented on torchmetrics/functional/pairwise/manhattan.py
> +def pairwise_manhattan_distance(
I see it was a typo originally, but still, we need to maintain back-compatibility, so can you add a warning and so on...

2022-01-12 11:43 UTC, Borda approved these changes

2022-01-12 11:49 UTC, rohitgr7 approved these changes

2022-01-12 11:49 UTC, rohitgr7 commented on torchmetrics/functional/pairwise/manhatten.py
> +        Use :func:`torchmetrics.functional.pairwise_manhatten_distance`. Will be removed in v0.8.
```suggestion
        Use :func:`torchmetrics.functional.pairwise_manhattan_distance`. Will be removed in v0.8.
```

2022-01-12 12:59 UTC, merged