Remove Python 3.10
PyTorchLightning/metrics pull request #810
Opened 2022-01-28 11:16 UTC by justusschock

## What does this PR do?

Fixes #808 

## Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

2022-01-28 12:01 UTC, Borda requested changes
I would be fine with removing the tag (even I do not like it)
but strongly disagree with a setting limitations for a user using it completely

2022-01-28 22:38 UTC, Borda commented
some quick notes on the building custom PT
```bash
pip install -q pyyaml
export USE_CUDA=0  # just to keep it simple
pip install git+https://github.com/pytorch/pytorch.git@v1.10.2
...
```

2022-01-31 09:44 UTC, Borda approved these changes

2022-01-31 09:59 UTC, SkafteNicki approved these changes

2022-01-31 09:59 UTC, SkafteNicki commented on docs/source/pages/quickstart.rst
> +    # Optional ig you do nt need compile GPU support
```suggestion
    # Optional if you do not need compile GPU support
```

2022-01-31 09:59 UTC, SkafteNicki commented on docs/source/pages/quickstart.rst
> +Eventually if there is missing PyTorch wheel for your OS or Python version you can simply compile `PyTorch from source`_:
```suggestion
Eventually if there is a missing PyTorch wheel for your OS or Python version you can simply compile `PyTorch from source`_:
```

2022-01-31 10:59 UTC, merged